### ISSUE TITLE
希望能一直做下去

### ISSUE THREAD

**Issue by rootdavid** [andurils/code-examples#1]
谢谢能有人从零开始搭建一个大型开源项目的例子，菜鸟真的能从里面学到很多知识，很感谢博主！希望这个系列能一直做下去。

**Comment by andurils** [comment]
十分高兴能对您带来帮助和收获，这也是写博文分享的目的之一——回顾自己，分享自己！
我也是第一次尝试写系列性的技术文章，有很多不足之处，像叙述方式、技术点的点面串联不知道有没有问题。
欢迎反馈啊！这是我最想要的！
谢谢您的肯定，我现在主要在 掘金平台 为主，也希望您能关注 给文章多点个赞，让更多的人能够看到，这样就反馈的声音就会更多！[https://juejin.cn/user/272334612084702](https://juejin.cn/user/272334612084702)   吐槽下掘金的流量是真的蛋疼。

**Comment by andurils** [comment]
新的文章正在写，因为到了阅读element源码的阶段了，如果只是文件夹一样介绍下，就脱离我一开始渐进式学习目标。
任何大的项目也不是一蹴而就成现如今的体量。我正在组织大纲，探索如何将源码一部部分解来渐进式的学习！
最近公司业务有点繁忙，估计要6月中旬左右会出来。
